---
# ============LICENSE_START=======================================================
#  Copyright (C) 2019 The Nordix Foundation. All rights reserved.
# ================================================================================
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
# ============LICENSE_END=========================================================

- name: Kill existing virtualbmc processes
  command: killall -w vbmcd
  args:
    removes: "{{ ansible_env.HOME }}/.vbmc/master.pid"
  ignore_errors: true

- name: Stop existing vbmcd service
  systemd:
    name: vbmcd
    enabled: false
    state: stopped
  ignore_errors: true

- name: Remove outdated virtualbmc folder
  file:
    path: "{{ ansible_env.HOME }}/.vbmc/"
    state: absent

- name: Ensure virtualbmc systemd service is configured
  template:
    src: vbmcd.service.j2
    dest: /etc/systemd/system/vbmcd.service
    owner: root
    group: root
    mode: 0644
    force: true

- name: Ensure virtualbmc systemd service is started and enabled
  systemd:
    name: vbmcd
    enabled: true
    state: restarted

- name: Create virtualbmc folder
  file:
    path: "{{ ansible_env.HOME }}/.vbmc/"
    state: directory

- name: Create vbmc configuration
  template:
    src: virtualbmc.conf.j2
    dest: "{{ ansible_env.HOME }}/.vbmc/virtualbmc.conf"

# vim: set ts=2 sw=2 expandtab:
