---
# ============LICENSE_START=======================================================
#  Copyright (C) 2019 The Nordix Foundation. All rights reserved.
# ================================================================================
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
# ============LICENSE_END=========================================================
- include_tasks: cleanup-bifrost.yml

- name: Clone bifrost repository and checkout '{{ bifrost_version }}'
  git:
    repo: "{{ bifrost_git_url }}"
    dest: "{{ engine_cache }}/repos/bifrost"
    version: "{{ bifrost_version }}"
    force: yes
  environment:
    http_proxy: "{{ lookup('env','http_proxy') }}"
    https_proxy: "{{ lookup('env','https_proxy') }}"
    no_proxy: "{{ lookup('env','no_proxy') }}"

- name: Install bifrost requirements
  pip:
    requirements: "{{ engine_cache }}/repos/bifrost/requirements.txt"
    extra_args: --upgrade

- name: Process PDF and IDF
  set_fact:
    num_nodes: "{{ nodes | length }}"
    hostnames: "{{ ('kubespray' in installer_type) | ternary(idf.kubespray.hostnames, idf.kolla.hostnames) }}"
    host_roles: "{{ ('kubespray' in installer_type) | ternary(idf.kubespray.nodes_roles, idf.kolla.nodes_roles) }}"
    networks: "{{ ('kubespray' in installer_type) | ternary(idf.kubespray.network, idf.kolla.network) }}"
    bifrost_inventory: {}

- name: Create bifrost static ips file {{ bifrost_staticips_file }}
  file:
    path: "{{ bifrost_staticips_file }}"
    state: touch
    mode: 0644

- include_tasks: create-dnsmasq-staticips.yml
  with_items: "{{ hostnames }}"
  loop_control:
    index_var: node_no

- name: Create DHCP hosts directory
  file:
    path: "/etc/dnsmasq.d/bifrost.dhcp-hosts.d"
    state: directory
    owner: "root"
    group: "root"
    mode: 0755
  become: yes

- name: Copy bifrost static ips file to DHCP hosts directory
  copy:
    src: "{{ bifrost_staticips_file }}"
    dest: /etc/dnsmasq.d/bifrost.dhcp-hosts.d/bifroststaticips
  become: yes

# vim: set ts=2 sw=2 expandtab:
